### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ScruffR** [adafruit/Adafruit_VL53L0X#1]
I'd like to "port" this library to put it onto the Particle Build IDE, but for that I'd like to provide a LICENSE file too.
I've downloaded the original [STM API](http://www.st.com/en/embedded-software/stsw-img005.html) which comes with this license agreement
http://www.st.com/resource/en/license_agreement/dm00299899.pdf

And your lib looks pretty similar, so I'm not sure what license to include in my "port" to keep everybody happy and stay out of trouble ;-)

**Comment by ladyada** [comment]
yah its just the STM api, so use that same license!
