### ISSUE TITLE
continuous ranging sample

### ISSUE THREAD

**Issue by gunnicus** [adafruit/Adafruit_VL53L0X#13]
Hi,

Is there a sample for continuous ranging mode?

Thanks

**Comment by JiroMusik** [comment]
No I feel like this API is very bad documented. I got my Sensor today but with the examples it says it isnt booting.
But the I2C Scanner finds the adress and sometimes I get values from the sensor. But I dont know where to look for info...

**Comment by JiroMusik** [comment]
Hi can you point us to mkore clear examples than the ones in the Library? I just want a continuous ranging and just want to mknow the Millimeter in every loop.

**Comment by caternuson** [comment]
New example added:
https://github.com/adafruit/Adafruit_VL53L0X/blob/master/examples/vl53l0x_continuous/vl53l0x_continuous.ino
