### ISSUE TITLE
Incorrect header paths in \core\ and \platform\

### ISSUE THREAD

**Issue by gergelytakacs** [adafruit/Adafruit_VL53L0X#14]
Problem: If one attempts to use this library as a part of another Arduino library, the sketch will not compile.
Reason: The source files in the \core and \platform contain header includes that do not have a path included, they point to header files within the same directory.
Solution:  
1. Add "../../" to header includes in  \core and \platform, or,
2.  consider changing the directory structure so that these source files are in the same directory with the headers.

**Comment by ladyada** [comment]
passes travis so mergin' :)
