### ISSUE TITLE
Not work with ESP32

### ISSUE THREAD

**Issue by maxpromer** [adafruit/Adafruit_VL53L0X#18]
Hello, i use this lib to read distance from VL53L0X. i use vl53l0x example to test but in serial monitor show
```
Adafruit VL53L0X test
Failed to boot VL53L0X
```
so i check communication between esp32 and VL53L0X via logic analyzer i found esp32 found 0x29 device address but in serial monitor show `Failed to boot`

How to fix this ?

Thanks !

**Comment by ladyada** [comment]
hiya, if you purchased the breakout from adafruit please post int he tech support forums. if you bought it elsewhere please post in their tech support forums. thanks!
