### ISSUE TITLE
Adafruit_VL53L0X.cpp file possible typo

### ISSUE THREAD

**Issue by mgulsoy** [adafruit/Adafruit_VL53L0X#25]
In the file Adafruit_VL53L0X.cpp at line 100 it is written:

`if( ( DeviceInfo.ProductRevisionMinor != 1 ) && ( DeviceInfo.ProductRevisionMinor != 1 ) )`

I think this line should be:

`if( ( DeviceInfo.ProductRevisionMajor != 1 ) && ( DeviceInfo.ProductRevisionMinor != 1 ) )`

**Comment by ladyada** [comment]
good question, does it still work for you if you change that line :)

**Comment by mgulsoy** [comment]
Yes, it works but with the newer v1.15 chips, this line could be an issue.

**Comment by ladyada** [comment]
ok then please remove the minor revision check and submit a PR, it doesnt make sense to fix a typo that then breaks the code

**Comment by mgulsoy** [comment]
Ok :) ( By the way, I admire your work @ladyada )

**Comment by ladyada** [comment]
thanks for the kind note! :)
