### ISSUE TITLE
Not getting by lox.begin()

### ISSUE THREAD

**Issue by ddritzenhoff** [adafruit/Adafruit_VL53L0X#32]
Hey,

I followed the setup for the vl53l0x as shown in --> https://learn.adafruit.com/adafruit-vl53l0x-micro-lidar-distance-sensor-breakout/arduino-code, but the program is not running correctly.
```
  Serial.println("Adafruit VL53L0X test");
  Serial.println("this is a test");
  if (!lox.begin()) {
    Serial.println("this failed to boot");
    Serial.println(F("Failed to boot VL53L0X"));
    while(1);
  }
  Serial.println("I got through the boot stage");
```
When I open the serial window, I get "Adafruit VL53L0X test" and "this is a test", but I don't get anything after that. This makes me think that the program is not getting by lox.begin().

Any advice?
Cheers

**Comment by ladyada** [comment]
hi if you purchased the sensor from adafruit, please post in the adafruit forums. if you purchased it elsewhere please contact that vendor for tech support :)
