### ISSUE TITLE
Comparision between two equal expressions in if statment

### ISSUE THREAD

**Issue by ViniciosSilva811** [adafruit/Adafruit_VL53L0X#37]
https://github.com/adafruit/Adafruit_VL53L0X/blob/7ea8e395dc4977aa69b1fb45af79161a120e42b7/src/Adafruit_VL53L0X.cpp#L110

There are two equal expressions in this if statment

**Comment by ladyada** [comment]
looks like the first one should be Major not Minor - wanna fix and submit a PR? :)

**Comment by ViniciosSilva811** [comment]
Ok

**Comment by ViniciosSilva811** [comment]
Do you need this pull request yet?

**Comment by ladyada** [comment]
got it - thanks :)
