### ISSUE TITLE
Why does this library depend on Adafruit SSD1306 and Adafruit GFX Library?

### ISSUE THREAD

**Issue by ViniciosSilva811** [adafruit/Adafruit_VL53L0X#40]
https://github.com/adafruit/Adafruit_VL53L0X/blob/e5bf0ba3cf77e0840a3d39bbb9cfa5b3f80b7580/library.properties#L10

**Comment by caternuson** [comment]
Those libraries are used by one of the examples:
https://github.com/adafruit/Adafruit_VL53L0X/blob/master/examples/vl53l0x_oled

**Comment by ViniciosSilva811** [comment]
Ok. Thaks to explain me @caternuson!
