### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by j3pic** [adafruit/Adafruit_VL53L0X#51]
I followed what claimed to be a link to documentation from [this page](https://www.arduino.cc/reference/en/libraries/adafruit_vl53l0x/) and ended up at this repo. But I don't see any documentation here. Where is it?

**Comment by ladyada** [comment]
https://learn.adafruit.com/adafruit-vl53l0x-micro-lidar-distance-sensor-breakout/arduino-code

**Comment by caternuson** [comment]
Also:
https://adafruit.github.io/Adafruit_VL53L0X/html/index.html
which you can get to from the doc badge in the README:
![image](https://user-images.githubusercontent.com/8755041/144929701-de809d13-5ce7-4ec9-b377-0b75bb007661.png)

**Comment by j3pic** [comment]
I didn't know that thing was a link.
