### ISSUE TITLE
For esp 8266 only two sensors are initialized

### ISSUE THREAD

**Issue by SergTopor** [adafruit/Adafruit_VL53L0X#61]
- Arduino board:  **ESP8266 NodeMCU Lolin (V3)**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **Arduino IDE 2.0.3**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **In examples vl53l0x_dual and vl53l0x_multi_extended_test are initialized 2 sensors VL53L0x only** 
  I don't know how to initialize 3 sensors.
  Thanks.

**Comment by caternuson** [comment]
Suggest using an I2C muxer if extending the existing examples is not achievable:
https://learn.adafruit.com/working-with-multiple-i2c-devices

Closing since not a library issue.
